In [28]:
from torchvision import datasets, transforms
import torch
import torch.utils.data
import pickle as pkl
import h5py

In [20]:
train = datasets.MNIST('/extra/yadongl10/data', train=True, download=False, transform=transforms.ToTensor())
data, label = train.data, train.targets


In [32]:
data.shape, label.shape, data[label==1].shape

(torch.Size([60000, 1, 28, 28]),
 torch.Size([60000]),
 torch.Size([6742, 1, 28, 28]))

In [40]:
data, label = data.numpy(), label.numpy()
with h5py.File('MNSIT_by_class.h5', 'w') as f:
    for i in range(10):
        f.create_dataset('{}_data'.format(i), data=data[label==i])
        f.create_dataset('{}_label'.format(i), data=label[label==i])

In [41]:
# check
with h5py.File('MNSIT_by_class.h5', 'r') as f:
    for i in f:
        print(i)

0_data
0_label
1_data
1_label
2_data
2_label
3_data
3_label
4_data
4_label
5_data
5_label
6_data
6_label
7_data
7_label
8_data
8_label
9_data
9_label


In [98]:
test = datasets.MNIST('/extra/yadongl10/data', train=False, download=False, transform=transforms.ToTensor())
data, label = test.data, test.targets


In [89]:
data, label = data.numpy(), label.numpy()
with h5py.File('MNSIT_by_class_test.h5', 'w') as f:
    for i in range(10):
        f.create_dataset('{}_data'.format(i), data=data[label==i])
        f.create_dataset('{}_label'.format(i), data=label[label==i])

In [47]:
x = torch.arange(10).view(2,5)
print(x)
_, index = torch.topk(x, 3, dim=1)
index

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


tensor([[4, 3, 2],
        [4, 3, 2]])

In [61]:
torch.mode(index, dim=1)

(tensor([2, 2]), tensor([2, 2]))

In [64]:
a = torch.tensor([[1,3,3],[2,2,4]])
torch.mode(a, dim=1)

(tensor([3, 2]), tensor([2, 1]))

In [103]:
(torch.arange(9)+1 == torch.arange(1,10)).sum()

tensor(9)

In [78]:
torch.arange(10).unsqueeze(1).repeat(1,10).view(-1)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4,
        4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9,
        9, 9, 9, 9])

In [102]:
torch.arange(9)+1 == torch.arange(1,10)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.uint8)

In [101]:
torch.arange(9), torch.arange(1,10)

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))